[options]
admin_passwd = $pbkdf2-sha512$600000$KEXo3VtLqfX.v7dWCoGw9g$.ipKu8mtx8E3j57o3VlTPRboQMMeGXXPTE3t3q.8uekruYF19VOocVwDVQLbUuO5CRhH.Vry6zy.eKLDuMXXNw
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
data_dir = /var/lib/odoo

